server:
  port: 8080

# Eureka Configuration
eureka:
  instance:
    hostname: gateway
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_HOST:registry}:${SERVICE_REGISTRY_PORT:8761}/eureka/
